version: "3.9"

services:
  web:
    build: .
    container_name: medical_app
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: >
      sh -c "
      cd medicalproject &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn medicalproject.wsgi:application
      --bind 0.0.0.0:8000
      --workers 3
      "

